version: '3.4'

services:
  speed:
    image: ${DOCKER_REGISTRY-}speedgovernor
    build:
      context: .
      dockerfile: src/Server/Dockerfile
  
    ports:
      - "5005:5005"
      - "5006:5006"
    depends_on:
      - db
    restart: on-failure
    container_name: speedgovernor

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    container_name: mssql